//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPic
    {
        public int HPID { get; set; }
        public string IMG { get; set; }
        public Nullable<int> HID { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
