//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.HotelPics = new HashSet<HotelPic>();
            this.Reviews = new HashSet<Review>();
            this.Rooms = new HashSet<Room>();
            this.Users = new HashSet<User>();
        }
    
        public int HID { get; set; }
        public string Hotelname { get; set; }
        public string Hotelchain { get; set; }
        public string City { get; set; }
        public string Streetname { get; set; }
        public string Country { get; set; }
        public Nullable<int> Stars { get; set; }
        public string Description { get; set; }
        public Nullable<int> HAID { get; set; }
    
        public virtual HotelAdmin HotelAdmin { get; set; }
        public virtual ICollection<HotelPic> HotelPics { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
