//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int HID { get; set; }
        public int UID { get; set; }
        public string Review_Text { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> TIME_CREATED { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}
